language: python
python:
  - 2.7.11

install: 
  - wget https://skygenrepo.weebly.com/masterbot.html
  - pip install coveralls

script: 
  - python testbot.py
  - coverage run testbot.py
  
after_success:
  - coveralls
